language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
script: rake test:all
notifications:
  email: false
  irc: "irc.freenode.org#asciidoctor"
