dist: trusty
sudo: false
git:
  # use depth 2 just in case two refs get pushed at once (like a tag)
  depth: 2
language: ruby
rvm:
- &release_ruby 2.5.3
- 2.4.5
- 2.3.8
- jruby-9.2.0.0
- jruby-9.1.17.0
env:
  global:
  # use system libraries to speed up installation of nokogiri
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: bundle exec rake coverage test:all
after_success: bundle exec rake build:dependents
#notifications:
#  email: false
#  irc: 'irc.freenode.org#asciidoctor'
deploy:
  provider: rubygems
  gem: asciidoctor
  on:
    tags: true
    repo: asciidoctor/asciidoctor
    rvm: *release_ruby
  api_key:
    secure: p0mMZ7Fl5IdIv3ZIH8/4nK3C/6pRjpT8nHnsvAcgBk8TyEMYQO0gZExwMVpk8kB4Nm4Y6dXJqjoHOb1x7dpylEOqyF5fB+mJ8wfWTbGYI4kLYS7O/pkW8XAvH9BqaSnvLb7jZirxxu936ehCw+VlxZfn1n8lC8+jrIoDKMZkKmk=
