version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  matrix:
    # there's a problem loading nokogiri 1.5.11 in Ruby 2.1 on Windows, so use Ruby 1.9.3
    #- ruby_version: '21'
    #- ruby_version: '21-x64'
    - ruby_version: '193'
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - bundle
build_script:
  - rake build
test_script:
  - rake test:all
artifacts:
  - path: pkg\*.gem
